ForumMVC.Web/Controllers/NavController.cs
using ForumMVC.BLL.Interfaces;
using ForumMVC.BLL.Service;
using ForumMVC.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ForumMVC.Web.Controllers
{
    public class NavController : Controller
    {
        // GET: Nav
        //public ActionResult Index()
        //{
        //    return View();
        //}
        IOrderService recordService;

        public NavController(IOrderService repo)
        {
            recordService = repo;
        }
        public PartialViewResult Menu(/*string topicname = null*/)
        {

            IEnumerable<string> topic = recordService.GetTopics()
             .Select(x => x.TopicName)
             .Distinct()
             .OrderBy(x => x);


            return PartialView(topic);
        }


        //public string Menu()
        //{
        //    return "Здесь будет меню";
        //}


        //// GET: Nav
        //public ActionResult Index()
        //{
        //    return View();
        //}


    }
}

ForumMVC.Web/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ForumMVC.Web.Controllers
{
    public class TopicController : Controller
    {
        // GET: Topic
        public ActionResult Index()
        {
            return View();
        }
    }
}

ForumMVC.Web/Views/Shared/_Layout - Копировать.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Форум пенсиоеров", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Форум", "List", "Topic")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ForumMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Форум пенсионеров@*@ViewBag.Title*@</title>
    <!--<link href="~/Content/Site.css" type="text/css" rel="stylesheet" />-->
    <!--   11   -->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Script/bootstrap")
</head>
<body>
    <div class="container-fluid  bg">
        <nav id="header" class="navbar">
            <div class="row  navbar-expand-md">
                <div class="col-sm-1"></div>
                <div class="col-md-3">
                    <a class="navbar-brand" href="#">Форум пенсионеров</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div><!-- /.col-md-3 -->
                <div class="col-lg-6" style="border:solid white 2px">
                    <div id="collapsingNavbar" class="navbar-collapse collapse">
                        <ul class="list-unstyled list-inline d-flex " style="border:solid red 2px">
                            <li class="nav-item active">@Html.ActionLink("Главная", "Index", "Home")</li>
                            <li class="nav-item-custom ">@Html.ActionLink("Условия", "About", "Home")</li>
                            <li class="nav-item ">@Html.ActionLink("Контакт", "Contact", "Home")</li>
                        </ul>
                    </div>
                </div><!-- /.col-lg-6 -->
                <div class="col-sm-2">
                    <ul>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Войти", "Login", "Account")</li>
                            <li>@Html.ActionLink("Регистрация", "Register", "Account")</li>
                        }
                        else
                        {
                            <li style="color:lightgray;">
                                <a>@Html.ViewBag.Greeting  @User.Identity.Name</a>
                            </li>
                            <li>@Html.ActionLink("Выход", "Logout", "Account")</li>
                        }
                    </ul>
                </div><!-- /.col-sm-2 -->
            </div><!-- row -->
        </nav><!-- /.navbar-collapse -->
        <div class="clearfix"> <hr></div>

        <div id="header_bottom" class="row">
            <div class="col-md-8">
                <div class="row"> <h2>Добро пожаловать на Форум</h2></div>
                <div class="row">
                    <div class="textwidget">
                        <h4>Поделитесь своим мнением и выпейте кружечку любимого кофе !</h4>
                    </div>
                    <div class="row">
                        <form role="search" method="get" id="bbp-search-form" action="http://dannci.wpmasters.org/wp-forum/forums/search/">
                            <div>
                                <label class="screen-reader-text hidden" for="bbp_search">Search for:</label>
                                <input type="hidden" name="action" value="bbp-search-request">
                                <input tabindex="101" type="text" value="" name="bbp_search" id="bbp_search">
                                <input tabindex="102" class="button" type="submit" id="bbp_search_submit" value="Search">
                            </div>
                        </form>
                    </div><!-- /.col-sm-1 -->
                </div>
            </div><!-- /.col-md-8 -->
            <div class="col-md-3 last bg-primary">
                <dl class="row" role="main">
                    <dt class="col-md-6">Registered Users</dt>
                    <dd class="col-md-6">
                        <strong>61</strong>
                    <dt class="col-md-6">Forums</dt>
                    <dd class="col-md-6">
                        <strong>5</strong>
                    </dd>
                    <dt class="col-md-6">Topics</dt>
                    <dd class="col-md-6">
                        <strong>23</strong>
                    </dd>
                    <dt class="col-md-6">Replies</dt>
                    <dd>
                        <strong>59</strong>
                    </dd>
                    <dt class="col-md-6">Topic Tags</dt>
                    <dd class="col-md-6">
                        <strong>22</strong>
                    </dd>
                </dl>
            </div><!-- /.col-md-3 -->
            <div class="col-1">&nbsp;</div>
        </div><!-- row -->
    </div><!-- /.container-fluid -->

    <div class="container-fluid body-content">
        <div id="categories">
            @{ Html.RenderAction("Menu", "Nav"); }
        </div>
        <div id="content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Simakovich ASP.NET Application</p>
            </footer>
        </div>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>